language: generic 
sudo: required
services:
  - docker

before_install:
  - docker buil -t kamwil314/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kamwil314/docker-react npm run test